version: "3.8"

services:
  ml-backend:
    container_name: ml-backend
    image: humansignal/ml-backend:v0
    build:
      context: .
      args:
        TEST_ENV: ${TEST_ENV}
    env_file:
      - .env
    environment:
      # Override any environment variables here if needed
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LABEL_STUDIO_URL=${LABEL_STUDIO_URL}
      - LABEL_STUDIO_API_KEY=${LABEL_STUDIO_API_KEY}
    ports:
      - "9090:9090"
    volumes:
      - "./data/server:/data"
